# bubbletea-charts - Copyright (c) 2024 Neomantra Corp.

version: '3'

tasks:
  default:
    desc: 'Default task runs the "build" task'
    deps:
      - build

  list:
    desc: 'Lists available tasks'
    cmds:
      - task --list-all

  dev-deps:
    desc: 'Install developer dependencies'
    cmds:
      - go install 'golang.org/x/tools/cmd/godoc@latest'

###############################################################################

  go-tidy:
    desc: 'Go tidy all the things'
    cmds:
      - go mod tidy

  go-update:
    desc: 'Go update all the dependencies'
    cmds:
      - go get -u ./...

  build:
    desc: 'Build all the things'
    deps:
      - build-cmds
      - build-examples

  clean:
    desc: 'Clean all'
    deps:
      - clean-examples

  go-doc-server:
    desc: 'Run Go documentation server'
    cmds:
      - echo 'http://localhost:6060/pkg/github.com/NimbleMarkets/bubbletea-charts/'
      - godoc -http=:6060
    deps:
      - dev-deps
      - go-tidy

###############################################################################
# Commands

  build-cmds:
    desc: 'Build all commands'
    deps:
      - build-cmd-btcharts-ohlc

  build-cmd-btcharts-ohlc:
    desc: 'Build btcharts-ohlc command'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-ohlc cmd/btcharts-ohlc/*.go
    sources:
      - cmd/btcharts-ohlc/*.go
      - canvas/**/*.go
      - linechart/**/*.go
    generates:
      - bin/btcharts-ohlc

###############################################################################
# Examples

  build-examples:
    desc: 'Build all examples'
    deps:
      - build-ex-barchart
      - build-ex-canvas
      - build-ex-graph
      - build-ex-linechart
      - build-ex-sparkline

  build-ex-barchart:
    desc: 'Build barchart examples'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-barchart-horizontal examples/barchart/horizontal/*.go
      - go build -o bin/btcharts-barchart-vertical examples/barchart/vertical/*.go
    sources:
      - barchart/**/*.go
      - canvas/**/*.go
      - examples/barchart/**/*.go
    generates:
      - bin/btcharts-barchart-horizontal
      - bin/btcharts-barchart-vertical

  build-ex-canvas:
    desc: 'Build canvas example'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-canvas-logo examples/canvas/logo/*.go
    sources:
      - examples/canvas/logo/*.go
      - canvas/**/*.go
    generates:
      - bin/btcharts-canvas-logo

  build-ex-graph:
    desc: 'Build graph examples'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-graph-braille examples/graph/braille/*.go
      - go build -o bin/btcharts-graph-circles examples/graph/circles/*.go
      - go build -o bin/btcharts-graph-columns examples/graph/columns/*.go
      - go build -o bin/btcharts-graph-lines examples/graph/lines/*.go
      - go build -o bin/btcharts-graph-rows examples/graph/rows/*.go
    sources:
      - canvas/**/*.go
      - examples/graph/**/*.go
    generates:
      - bin/btcharts-graph-braille
      - bin/btcharts-graph-circles
      - bin/btcharts-graph-columns
      - bin/btcharts-graph-lines
      - bin/btcharts-graph-rows

  build-ex-linechart:
    desc: 'Build linechart examples'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-linechart-circles examples/linechart/circles/*.go
      - go build -o bin/btcharts-linechart-lines examples/linechart/lines/*.go
      - go build -o bin/btcharts-linechart-scatter examples/linechart/scatter/*.go
      - go build -o bin/btcharts-linechart-streaming examples/linechart/streaming/*.go
      - go build -o bin/btcharts-linechart-timeseries examples/linechart/timeseries/*.go
      - go build -o bin/btcharts-linechart-wavelines examples/linechart/wavelines/*.go
    sources:
      - canvas/**/*.go
      - examples/linechart/**/*.go
      - linechart/**/*.go
    generates:
      - bin/btcharts-linechart-circles
      - bin/btcharts-linechart-lines
      - bin/btcharts-linechart-scatter
      - bin/btcharts-linechart-streaming
      - bin/btcharts-linechart-timeseries
      - bin/btcharts-linechart-wavelines

  build-ex-sparkline:
    desc: 'Build sparkline example'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-sparkline examples/sparkline/*.go
    sources:
      - canvas/**/*.go
      - examples/sparkline/*.go
      - sparkline/**/*.go
    generates:
      - bin/btcharts-sparkline

  clean-examples:
    desc: 'Removes all examples from bin'
    cmds:
      - rm -f bin/btcharts-barchart-horizontal bin/btcharts-barchart-vertical
      - rm -f bin/btcharts-canvas-logo
      - rm -f bin/btcharts-graph-braille bin/btcharts-graph-circles bin/btcharts-graph-columns bin/btcharts-graph-lines bin/btcharts-graph-rows
      - rm -f bin/btcharts-linechart-circles bin/btcharts-linechart-lines bin/btcharts-linechart-scatter bin/btcharts-linechart-streaming bin/btcharts-linechart-timeseries bin/btcharts-linechart-wavelines
      - rm -f bin/btcharts-sparkline
