# bubbletea-charts - Copyright (c) 2024 Neomantra Corp.

version: '3'

tasks:
  default:
    desc: 'Default task runs the "build" task'
    deps:
      - build

  list:
    desc: 'Lists available tasks'
    cmds:
      - task --list-all

  dev-deps:
    desc: 'Install developer dependencies'
    cmds:
      - go install 'golang.org/x/tools/cmd/godoc@latest'

###############################################################################

  go-tidy:
    desc: 'Go tidy all the things'
    cmds:
      - go mod tidy

  go-update:
    desc: 'Go update all the dependencies'
    cmds:
      - go get -u ./...

  build:
    desc: 'Build all the things'
    deps:
      - build-cmds
      - build-examples

  clean:
    desc: 'Clean commands and examples)'
    deps:
      - clean-cmds
      - clean-examples

  go-doc-server:
    desc: 'Run Go documentation server'
    cmds:
      - echo 'http://localhost:6060/pkg/github.com/NimbleMarkets/bubbletea-charts/'
      - godoc -http=:6060
    deps:
      - dev-deps
      - go-tidy

###############################################################################
# Commands

  build-cmds:
    desc: 'Build all commands'
    deps:
      - build-cmd-btcharts-ohlc

  build-cmd-btcharts-ohlc:
    desc: 'Build btcharts-ohlc command'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-ohlc cmd/btcharts-ohlc/*.go
    sources:
      - cmd/btcharts-ohlc/*.go
      - canvas/**/*.go
      - linechart/**/*.go
    generates:
      - bin/btcharts-ohlc

  clean-cmds:
    desc: 'Cleans all commands'
    cmds:
      - rm bin/btcharts-ohlc
    
###############################################################################
# Examples

  build-examples:
    desc: 'Build all examples'
    deps:
      - build-ex-barchart
      - build-ex-canvas
      - build-ex-graph
      - build-ex-linechart
      - build-ex-quickstart
      - build-ex-sparkline

  build-ex-barchart:
    desc: 'Build barchart examples'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-barchart-horizontal examples/barchart/horizontal/*.go
      - go build -o bin/btcharts-barchart-vertical examples/barchart/vertical/*.go
    sources:
      - barchart/**/*.go
      - canvas/**/*.go
      - examples/barchart/**/*.go
    generates:
      - bin/btcharts-barchart-horizontal
      - bin/btcharts-barchart-vertical

  build-ex-canvas:
    desc: 'Build canvas example'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-canvas-logo examples/canvas/logo/*.go
    sources:
      - examples/canvas/logo/*.go
      - canvas/**/*.go
    generates:
      - bin/btcharts-canvas-logo

  build-ex-graph:
    desc: 'Build graph examples'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-graph-braille examples/graph/braille/*.go
      - go build -o bin/btcharts-graph-circles examples/graph/circles/*.go
      - go build -o bin/btcharts-graph-columns examples/graph/columns/*.go
      - go build -o bin/btcharts-graph-lines examples/graph/lines/*.go
      - go build -o bin/btcharts-graph-rows examples/graph/rows/*.go
    sources:
      - canvas/**/*.go
      - examples/graph/**/*.go
    generates:
      - bin/btcharts-graph-braille
      - bin/btcharts-graph-circles
      - bin/btcharts-graph-columns
      - bin/btcharts-graph-lines
      - bin/btcharts-graph-rows

  build-ex-linechart:
    desc: 'Build linechart examples'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-linechart-circles examples/linechart/circles/*.go
      - go build -o bin/btcharts-linechart-lines examples/linechart/lines/*.go
      - go build -o bin/btcharts-linechart-scatter examples/linechart/scatter/*.go
      - go build -o bin/btcharts-linechart-streaming examples/linechart/streaming/*.go
      - go build -o bin/btcharts-linechart-timeseries examples/linechart/timeseries/*.go
      - go build -o bin/btcharts-linechart-wavelines examples/linechart/wavelines/*.go
    sources:
      - canvas/**/*.go
      - examples/linechart/**/*.go
      - linechart/**/*.go
    generates:
      - bin/btcharts-linechart-circles
      - bin/btcharts-linechart-lines
      - bin/btcharts-linechart-scatter
      - bin/btcharts-linechart-streaming
      - bin/btcharts-linechart-timeseries
      - bin/btcharts-linechart-wavelines

  build-ex-quickstart:
    desc: 'Build quickstart example'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-quickstart examples/quickstart/*.go
    sources:
      - canvas/**/*.go
      - examples/quickstart/*.go
      - linechart/**/*.go
    generates:
      - bin/btcharts-quickstart

  build-ex-sparkline:
    desc: 'Build sparkline example'
    deps: [go-tidy]
    cmds:
      - go build -o bin/btcharts-sparkline examples/sparkline/*.go
    sources:
      - canvas/**/*.go
      - examples/sparkline/*.go
      - sparkline/**/*.go
    generates:
      - bin/btcharts-sparkline

  clean-examples:
    desc: 'Removes all examples from bin'
    cmds:
      - rm -f bin/btcharts-barchart-horizontal bin/btcharts-barchart-vertical
      - rm -f bin/btcharts-canvas-logo
      - rm -f bin/btcharts-graph-braille bin/btcharts-graph-circles bin/btcharts-graph-columns bin/btcharts-graph-lines bin/btcharts-graph-rows
      - rm -f bin/btcharts-linechart-circles bin/btcharts-linechart-lines bin/btcharts-linechart-scatter bin/btcharts-linechart-streaming bin/btcharts-linechart-timeseries bin/btcharts-linechart-wavelines
      - rm -f bin/btcharts-quickstart
      - rm -f bin/btcharts-sparkline

###############################################################################
# GIF Generation from VHS Cassettes

  deps-gifs:
    desc: 'Install dependencies for GIF generation'
    cmds:
      - go install github.com/charmbracelet/vhs@latest
      - brew install imagemagick

  validate-tapes:
    desc: 'Validate vhs tapes for GIF generation'
    cmds:
      - vhs validate ./cmd/btcharts-ohlc/demo.tape
      - vhs validate ./examples/barchart/horizontal/demo.tape
      - vhs validate ./examples/barchart/vertical/demo.tape
      - vhs validate ./examples/canvas/logo/demo.tape
      - vhs validate ./examples/graph/braille/demo.tape
      - vhs validate ./examples/graph/circles/demo.tape
      - vhs validate ./examples/graph/columns/demo.tape
      - vhs validate ./examples/graph/lines/demo.tape
      - vhs validate ./examples/graph/rows/demo.tape
      - vhs validate ./examples/linechart/circles/demo.tape
      - vhs validate ./examples/linechart/lines/demo.tape
      - vhs validate ./examples/linechart/scatter/demo.tape
      - vhs validate ./examples/linechart/streaming/demo.tape
      - vhs validate ./examples/linechart/timeseries/demo.tape
      - vhs validate ./examples/linechart/wavelines/demo.tape
      - vhs validate ./examples/quickstart/demo.tape
      - vhs validate ./examples/sparkline/demo.tape
    sources:
      - ./**/*.tape

  build-gifs:
    desc: 'Build vhs cassette gifs'
    deps: [build, validate-tapes]
    cmds:
      - vhs --output ./cmd/btcharts-ohlc/demo.gif ./cmd/btcharts-ohlc/demo.tape
      - vhs --output ./examples/barchart/horizontal/demo.gif ./examples/barchart/horizontal/demo.tape
      - vhs --output ./examples/barchart/vertical/demo.gif ./examples/barchart/vertical/demo.tape
      - vhs --output ./examples/canvas/logo/demo.gif ./examples/canvas/logo/demo.tape
      - vhs --output ./examples/graph/braille/demo.gif ./examples/graph/braille/demo.tape
      - vhs --output ./examples/graph/circles/demo.gif ./examples/graph/circles/demo.tape
      - vhs --output ./examples/graph/columns/demo.gif ./examples/graph/columns/demo.tape
      - vhs --output ./examples/graph/lines/demo.gif ./examples/graph/lines/demo.tape
      - vhs --output ./examples/graph/rows/demo.gif ./examples/graph/rows/demo.tape
      - vhs --output ./examples/linechart/circles/demo.gif ./examples/linechart/circles/demo.tape
      - vhs --output ./examples/linechart/lines/demo.gif ./examples/linechart/lines/demo.tape
      - vhs --output ./examples/linechart/scatter/demo.gif ./examples/linechart/scatter/demo.tape
      - vhs --output ./examples/linechart/streaming/demo.gif ./examples/linechart/streaming/demo.tape
      - vhs --output ./examples/linechart/timeseries/demo.gif ./examples/linechart/timeseries/demo.tape
      - vhs --output ./examples/linechart/wavelines/demo.gif ./examples/linechart/wavelines/demo.tape
      - vhs --output ./examples/quickstart/demo.gif ./examples/quickstart/demo.tape
      - vhs --output ./examples/sparkline/demo.gif ./examples/sparkline/demo.tape
    sources:
      - ./**/*.tape
    generates:
      - ./cmd/btcharts-ohlc/demo.gif
      - ./examples/barchart/horizontal/demo.gif
      - ./examples/barchart/vertical/demo.gif
      - ./examples/canvas/logo/demo.gif
      - ./examples/graph/braille/demo.gif
      - ./examples/graph/circles/demo.gif
      - ./examples/graph/columns/demo.gif
      - ./examples/graph/lines/demo.gif
      - ./examples/graph/rows/demo.gif
      - ./examples/linechart/circles/demo.gif
      - ./examples/linechart/lines/demo.gif
      - ./examples/linechart/scatter/demo.gif
      - ./examples/linechart/streaming/demo.gif
      - ./examples/linechart/timeseries/demo.gif
      - ./examples/linechart/wavelines/demo.gif
      - ./examples/sparkline/demo.gif

  clean-gifs:
    desc: 'Cleans vhs cassette gifs'
    cmds:
      - rm -f ./cmd/btcharts-ohlc/demo.gif
      - rm -f ./examples/barchart/horizontal/demo.gif
      - rm -f ./examples/barchart/vertical/demo.gif
      - rm -f ./examples/canvas/logo/demo.gif
      - rm -f ./examples/graph/braille/demo.gif
      - rm -f ./examples/graph/circles/demo.gif
      - rm -f ./examples/graph/columns/demo.gif
      - rm -f ./examples/graph/lines/demo.gif
      - rm -f ./examples/graph/rows/demo.gif
      - rm -f ./examples/linechart/circles/demo.gif
      - rm -f ./examples/linechart/lines/demo.gif
      - rm -f ./examples/linechart/scatter/demo.gif
      - rm -f ./examples/linechart/streaming/demo.gif
      - rm -f ./examples/linechart/timeseries/demo.gif
      - rm -f ./examples/linechart/wavelines/demo.gif
      - rm -f ./examples/quickstart/demo.gif
      - rm -f ./examples/sparkline/demo.gif